DROP TABLE status_log CASCADE CONSTRAINTS;
DROP TABLE obavestenje CASCADE CONSTRAINTS;
DROP TABLE dokument_aktivni_fajl CASCADE CONSTRAINTS;
DROP TABLE dokument_fajl CASCADE CONSTRAINTS;
DROP TABLE revizija_izmena CASCADE CONSTRAINTS;
DROP TABLE korisnik_dokument CASCADE CONSTRAINTS;
DROP TABLE dokument_zavisnost CASCADE CONSTRAINTS;
DROP TABLE dokument_revizija CASCADE CONSTRAINTS;
DROP TABLE dokument CASCADE CONSTRAINTS;
DROP TABLE tok_status CASCADE CONSTRAINTS;
DROP TABLE status CASCADE CONSTRAINTS;
DROP TABLE fajl CASCADE CONSTRAINTS;
DROP TABLE korisnik_projekat CASCADE CONSTRAINTS;
DROP TABLE projekat CASCADE CONSTRAINTS;
DROP TABLE tok CASCADE CONSTRAINTS;


CREATE TABLE projekat (
                          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          naziv varchar(255) NOT NULL,
                          status nvarchar2(255) NOT NULL CHECK (status IN ('zavrsen', 'obustavljen','u_toku')),
                          rok_zavrsetka date NOT NULL,
                          tok_projekta_id integer,
                          procenat_zavrsenosti float
);

CREATE TABLE korisnik_projekat (
                                   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   korisnik_id integer,
                                   projekat_id integer,
                                   uloga_u_projektu nvarchar2(255) NOT NULL CHECK (uloga_u_projektu IN ('vodja', 'clan','menadzer')),
                                   CONSTRAINT uq_korisnik_projekat UNIQUE (korisnik_id, projekat_id)
                               );

CREATE TABLE tok (
                     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     naziv varchar(255)
);

CREATE TABLE status (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        naziv varchar(255),
                        potrebno_odobrenje_za_prelazak NUMBER(1) CHECK (potrebno_odobrenje_za_prelazak IN (0,1)),
                        dozvola_menjanja_za_vlasnika   NUMBER(1) CHECK (dozvola_menjanja_za_vlasnika IN (0,1)),
                        dozvola_dodavanja_za_vlasnika  NUMBER(1) CHECK (dozvola_dodavanja_za_vlasnika IN (0,1)),
                        dozvola_brisanja_za_vlasnika   NUMBER(1) CHECK (dozvola_brisanja_za_vlasnika IN (0,1)),
                        dozvola_citanja_za_vlasnika    NUMBER(1) CHECK (dozvola_citanja_za_vlasnika IN (0,1)),
                        dozvola_menjanja_za_zaduzenog  NUMBER(1) CHECK (dozvola_menjanja_za_zaduzenog IN (0,1)),
                        dozvola_dodavanja_za_zaduzenog NUMBER(1) CHECK (dozvola_dodavanja_za_zaduzenog IN (0,1)),
                        dozvola_brisanja_za_zaduzenog  NUMBER(1) CHECK (dozvola_brisanja_za_zaduzenog IN (0,1)),
                        dozvola_citanja_za_zaduzenog   NUMBER(1) CHECK (dozvola_citanja_za_zaduzenog IN (0,1))
);

CREATE TABLE tok_status (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tok_id integer,
                            trenutno_stanje integer,
                            sledece_stanje integer,
                            status_nakon_odbijanja integer
);

CREATE TABLE dokument (
                          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          projekat_id integer,
                          naziv varchar(255),
                          opis varchar(255),
                          tok_izrade_dokumenta integer,
                          status integer,
                          prioritet nvarchar2(255) NOT NULL CHECK (prioritet IN ('visok', 'srednji', 'mali')),
                          roditelj_dokument_id integer,
                          rok_zavrsetka date NOT NULL,
                          glavni_fajl_id integer,
                          vlasnik integer,
                          pripremna_verzija NUMBER(1) CHECK (pripremna_verzija IN (0,1)),
                          posledjna_izmena date,
                          izmena_od integer,
                          procenat_zavrsenosti float

);

CREATE TABLE dokument_revizija (
                                   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   dokument_id integer,
                                   odobreno NUMBER(1) CHECK (odobreno IN (0,1)),
                                   trenutni_status integer,
                                   pregledac_id integer
);

CREATE TABLE dokument_zavisnost (
                                    dokument_id integer,
                                    zavisi_od integer,
                                    CONSTRAINT pk_dokument_zavisnost PRIMARY KEY (dokument_id, zavisi_od)
);

CREATE TABLE korisnik_dokument (
                                   korisnik_id integer,
                                   dokument_id integer,
                                   CONSTRAINT pk_korisnik_dokument PRIMARY KEY (korisnik_id, dokument_id)
);

CREATE TABLE revizija_izmena (
                                 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 revizija_id integer,
                                 izmena varchar(255),
                                 ispravljena NUMBER(1) CHECK (ispravljena IN (0,1)),
                                 datum_ispravljanja date
);

CREATE TABLE dokument_fajl (
                               dokument_id integer,
                               fajl_id integer,
                               CONSTRAINT pk_dokument_fajl PRIMARY KEY (dokument_id, fajl_id)
);


CREATE TABLE dokument_aktivni_fajl (
                                       dokument_id integer,
                                       fajl_id integer,
                                       CONSTRAINT pk_dokument_aktivni_fajl PRIMARY KEY (dokument_id, fajl_id)
);

CREATE TABLE fajl (
                      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      podatak blob,
                      verzija integer,
                      datum_kreiranja TIMESTAMP,
                      naziv VARCHAR2(255),
                      ekstenzija varchar2(15)
);

CREATE TABLE obavestenje (
                             id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             poruka varchar(255),
                             korisnik_id integer,
                             procitana NUMBER(1) CHECK (procitana IN (0,1)),
                             dokument_id integer
);

CREATE TABLE status_log (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            datum TIMESTAMP,
                            izvrsilac integer,
                            dokument integer,
                            projekat_id integer,
                            prethodno_stanje integer,
                            novo_stanje integer
);

ALTER TABLE projekat ADD FOREIGN KEY (tok_projekta_id) REFERENCES tok (id);
ALTER TABLE korisnik_projekat ADD FOREIGN KEY (projekat_id) REFERENCES projekat (id);
ALTER TABLE tok_status ADD FOREIGN KEY (tok_id) REFERENCES tok (id);
ALTER TABLE tok_status ADD FOREIGN KEY (trenutno_stanje) REFERENCES status (id);
ALTER TABLE tok_status ADD FOREIGN KEY (sledece_stanje) REFERENCES tok_status (id);
ALTER TABLE tok_status ADD FOREIGN KEY (status_nakon_odbijanja) REFERENCES tok_status (id);
ALTER TABLE dokument ADD FOREIGN KEY (projekat_id) REFERENCES projekat (id);
ALTER TABLE dokument ADD FOREIGN KEY (tok_izrade_dokumenta) REFERENCES tok (id);
ALTER TABLE dokument ADD FOREIGN KEY (status) REFERENCES tok_status (id);
ALTER TABLE dokument ADD FOREIGN KEY (roditelj_dokument_id) REFERENCES dokument (id);
ALTER TABLE dokument ADD FOREIGN KEY (vlasnik) REFERENCES korisnik_projekat (id);
ALTER TABLE dokument ADD FOREIGN KEY (glavni_fajl_id) REFERENCES fajl (id);
ALTER TABLE dokument ADD FOREIGN KEY (izmena_od) REFERENCES korisnik_projekat (id);
ALTER TABLE dokument_revizija ADD FOREIGN KEY (dokument_id) REFERENCES dokument (id);
ALTER TABLE dokument_revizija ADD FOREIGN KEY (trenutni_status) REFERENCES tok_status (id);
ALTER TABLE dokument_revizija ADD FOREIGN KEY (pregledac_id) REFERENCES korisnik_projekat (id);
ALTER TABLE dokument_zavisnost ADD FOREIGN KEY (dokument_id) REFERENCES dokument (id);
ALTER TABLE dokument_zavisnost ADD FOREIGN KEY (zavisi_od) REFERENCES dokument (id);
ALTER TABLE korisnik_dokument ADD FOREIGN KEY (korisnik_id) REFERENCES korisnik_projekat (id);
ALTER TABLE korisnik_dokument ADD FOREIGN KEY (dokument_id) REFERENCES dokument (id);
ALTER TABLE revizija_izmena ADD FOREIGN KEY (revizija_id) REFERENCES dokument_revizija (id);
ALTER TABLE dokument_fajl ADD FOREIGN KEY (dokument_id) REFERENCES dokument (id);
ALTER TABLE dokument_fajl ADD FOREIGN KEY (fajl_id) REFERENCES fajl (id);
ALTER TABLE dokument_aktivni_fajl ADD FOREIGN KEY (dokument_id) REFERENCES dokument (id);
ALTER TABLE dokument_aktivni_fajl ADD FOREIGN KEY (fajl_id) REFERENCES fajl (id);
ALTER TABLE obavestenje ADD FOREIGN KEY (dokument_id) REFERENCES dokument (id);
ALTER TABLE status_log ADD FOREIGN KEY (izvrsilac) REFERENCES korisnik_projekat (id);
ALTER TABLE status_log ADD FOREIGN KEY (dokument) REFERENCES dokument (id);
ALTER TABLE status_log ADD FOREIGN KEY (prethodno_stanje) REFERENCES tok_status (id);
ALTER TABLE status_log ADD FOREIGN KEY (novo_stanje) REFERENCES tok_status (id);
ALTER TABLE status_log ADD FOREIGN KEY (projekat_id) REFERENCES projekat (id);
