server:
  port: 9090


spring:
  application:
    name: timeseries-database-service
  influx:
    token: my-super-secret-auth-token
    bucket: nais_bucket
    org: nais_org
    url: http://influxdb:8086
    user: nais
    password: password
