server:
  port: ${GATEWAY_PORT:9000}

spring:
  application:
    name: ${APP_NAME:gateway-api}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: writing-assistant-service
          uri: ${WRITING_ASSISTANT_URL:http://localhost:8000/writing-assistant}
          predicates:
            - Path=/writing-assistant/**
          filters:
            - name: UserManagementAuth

        - id: document-preparation-service
          uri: ${DOCUMENT_PREPARATION_URL:http://localhost:8005/api/docPrep}
          predicates:
            - Path=/api/docPrep/**
          filters:
            - name: UserManagementAuth

        - id: project-realization-service
          uri: ${PROJECT_REALIZATION_URL:http://localhost:8006/project-realization}
          predicates:
            - Path=/project-realization/**
          filters:
            - name: UserManagementAuth

        - id: document-management-service
          uri: ${DOCUMENT_MANAGEMENT_URL:http://localhost:8081/document-management}
          predicates:
            - Path=/document-management/**
          filters:
            - name: UserManagementAuth

        - id: user-management-service
          uri: ${USER_MANAGEMENT_URL:http://localhost:8007/}
          predicates:
            - Path=/auth/**
